// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2zk-C4_2yxPnI34q4qdKqheHqEcn9sI',
    appId: '1:749359220248:web:1d7db2950e80258ad2656d',
    messagingSenderId: '749359220248',
    projectId: 'library-c06d2',
    authDomain: 'library-c06d2.firebaseapp.com',
    databaseURL: 'https://library-c06d2.firebaseio.com',
    storageBucket: 'library-c06d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNN9ooAWGNToERUpL8zQi-It5c_8H3M4',
    appId: '1:749359220248:android:9ca7615250321242d2656d',
    messagingSenderId: '749359220248',
    projectId: 'library-c06d2',
    databaseURL: 'https://library-c06d2.firebaseio.com',
    storageBucket: 'library-c06d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_XBGf0KKxNseeqJsdoR3uwmiu-717BWU',
    appId: '1:749359220248:ios:e355f8f84e533790d2656d',
    messagingSenderId: '749359220248',
    projectId: 'library-c06d2',
    databaseURL: 'https://library-c06d2.firebaseio.com',
    storageBucket: 'library-c06d2.appspot.com',
    iosClientId: '749359220248-iqmqrkdst0stm3lbnaa7puaim4oqrahc.apps.googleusercontent.com',
    iosBundleId: 'com.web.expertgraphweb',
  );
}
